#!/bin/sh

PROG=find-and-replace
DIR="$(cd "$(dirname "$0")" && pwd)"
OUTDIR="${COVERAGE_OUTDIR:-$DIR}"
CFLAGS='-march=native -O2 -Wpedantic -pedantic -Wall -Wextra -Wuninitialized -Wshadow -Warray-bounds -Wnull-dereference -Wformat -Wunused -Wwrite-strings'
# CFLAGS='-march=native -O2 -Wpedantic -pedantic -Wall -Wextra -Wuninitialized -Wshadow -Warray-bounds -Wnull-dereference -Wformat -Wunused -Wwrite-strings -fanalyzer'
LFLAGS=""
CC=$(readlink "$(command -v cc)")
if [ "$COVERAGE" = "1" ]; then
	CFLAGS="-O0 --coverage"
	LFLAGS="--coverage"
fi
#shellcheck disable=SC2086
cc "$DIR/$PROG.c" -o "$OUTDIR/$PROG" $CFLAGS -I"$DIR/lib/jstring/build/include" -L"$DIR/lib/jstring/build/lib" -Wl,-rpath,"$DIR/lib/jstring/build/lib" -ljstr $LFLAGS || exit
echo "cc $DIR/$PROG.c -o $DIR/$PROG $CFLAGS -ljstr $LFLAGS"
