#!/bin/sh

PROG=find-and-replace
CFLAGS='-O2 -g'
LFLAGS="$LD_LIBRARY_PATH -ljstr"
CC=$(readlink "$(command -v cc)")
if [ "$CC" = 'gcc' ] || [ "$CC" = 'clang' ]; then
	CFLAGS="$CFLAGS -march=native -Wall -Wextra -Wpedantic"
fi
#shellcheck disable=SC2086
cc $PROG.c -o $PROG $CFLAGS $LFLAGS || exit
echo "cc $PROG.c -o $PROG $CFLAGS $LFLAGS"
