#!/bin/sh
SOURCE=main.c
README_SRC=.README.md
README_DST=README.md
cat "$README_SRC" > "$README_DST"
usage_str=$(grep '[^0-9A-Za-z_]_("' "$SOURCE" | sed 's/.*_("//; s/\\n".*//; s/\\\\/\\/g; s/ find-and-replace/\n\n```\nfind-and-replace/')
printf '\n## %s\n```\n' "$usage_str" >> "$README_DST"
