#!/bin/sh
SOURCE=find-and-replace.c
README_SRC=.README.md
README_DST=README.md
cat "$README_SRC" > "$README_DST"
echo "" >> "$README_DST"
echo "## Usage:" >> "$README_DST"
echo "" >> "$README_DST"
echo "\`\`\`" >> "$README_DST"
grep '[^0-9A-Za-z_]_("' "$SOURCE" | sed 's/.*_("//; s/\\n".*//; s/\\\\/\\/g' >> "$README_DST"
echo "\`\`\`" >> "$README_DST"
