#!/bin/sh
SOURCE=find-and-replace.c
README_SRC=.README.md
README_DST=README.md
cat "$README_SRC" > "$README_DST"
echo "## $(grep '[^0-9A-Za-z_]_("' "$SOURCE" | sed 's/.*_("//; s/\\n".*/<br>/; s/\\\\/\\/g; s/ find-and-replace/\nfind-and-replace/; s/\([()_]\)/\\\1/g; s/\[/\\[/g; s/\]/\\]/g')" >> "$README_DST"
